declare var foundry: any;
declare var Hooks: any;
declare var game: any;
declare var ui: any;
declare var CONST: any;
declare var saveDataToFile: any;
declare var Playlist: any;
declare var CombatMusicMaster: any;
declare var CONFIG: any;
